INSERT INTO public.countries (id, full_name, short_name) VALUES (1, 'Andorra', 'AD');
INSERT INTO public.countries (id, full_name, short_name) VALUES (2, 'United Arab Emirates', 'AE');
INSERT INTO public.countries (id, full_name, short_name) VALUES (3, 'Afghanistan', 'AF');
INSERT INTO public.countries (id, full_name, short_name) VALUES (4, 'Antigua and Barbuda', 'AG');
INSERT INTO public.countries (id, full_name, short_name) VALUES (5, 'Anguilla', 'AI');
INSERT INTO public.countries (id, full_name, short_name) VALUES (6, 'Albania', 'AL');
INSERT INTO public.countries (id, full_name, short_name) VALUES (7, 'Armenia', 'AM');
INSERT INTO public.countries (id, full_name, short_name) VALUES (8, 'Angola', 'AO');
INSERT INTO public.countries (id, full_name, short_name) VALUES (9, 'Antarctica', 'AQ');
INSERT INTO public.countries (id, full_name, short_name) VALUES (10, 'Argentina', 'AR');
INSERT INTO public.countries (id, full_name, short_name) VALUES (11, 'American Samoa', 'AS');
INSERT INTO public.countries (id, full_name, short_name) VALUES (12, 'Austria', 'AT');
INSERT INTO public.countries (id, full_name, short_name) VALUES (13, 'Australia', 'AU');
INSERT INTO public.countries (id, full_name, short_name) VALUES (14, 'Aruba', 'AW');
INSERT INTO public.countries (id, full_name, short_name) VALUES (15, 'Åland Islands', 'AX');
INSERT INTO public.countries (id, full_name, short_name) VALUES (16, 'Azerbaijan', 'AZ');
INSERT INTO public.countries (id, full_name, short_name) VALUES (17, 'Bosnia and Herzegovina', 'BA');
INSERT INTO public.countries (id, full_name, short_name) VALUES (18, 'Barbados', 'BB');
INSERT INTO public.countries (id, full_name, short_name) VALUES (19, 'Bangladesh', 'BD');
INSERT INTO public.countries (id, full_name, short_name) VALUES (20, 'Belgium', 'BE');
INSERT INTO public.countries (id, full_name, short_name) VALUES (21, 'Burkina Faso', 'BF');
INSERT INTO public.countries (id, full_name, short_name) VALUES (22, 'Bulgaria', 'BG');
INSERT INTO public.countries (id, full_name, short_name) VALUES (23, 'Bahrain', 'BH');
INSERT INTO public.countries (id, full_name, short_name) VALUES (24, 'Burundi', 'BI');
INSERT INTO public.countries (id, full_name, short_name) VALUES (25, 'Benin', 'BJ');
INSERT INTO public.countries (id, full_name, short_name) VALUES (26, 'Saint Barthélemy', 'BL');
INSERT INTO public.countries (id, full_name, short_name) VALUES (27, 'Bermuda', 'BM');
INSERT INTO public.countries (id, full_name, short_name) VALUES (28, 'Brunei Darussalam', 'BN');
INSERT INTO public.countries (id, full_name, short_name) VALUES (29, 'Bolivia (Plurinational State of)', 'BO');
INSERT INTO public.countries (id, full_name, short_name) VALUES (30, 'Bonaire', 'BQ');
INSERT INTO public.countries (id, full_name, short_name) VALUES (31, 'Brazil', 'BR');
INSERT INTO public.countries (id, full_name, short_name) VALUES (32, 'Bahamas', 'BS');
INSERT INTO public.countries (id, full_name, short_name) VALUES (33, 'Bhutan', 'BT');
INSERT INTO public.countries (id, full_name, short_name) VALUES (34, 'Botswana', 'BW');
INSERT INTO public.countries (id, full_name, short_name) VALUES (35, 'Belarus', 'BY');
INSERT INTO public.countries (id, full_name, short_name) VALUES (36, 'Belize', 'BZ');
INSERT INTO public.countries (id, full_name, short_name) VALUES (37, 'Canada', 'CA');
INSERT INTO public.countries (id, full_name, short_name) VALUES (38, 'Cocos (Keeling) Islands', 'CC');
INSERT INTO public.countries (id, full_name, short_name) VALUES (39, 'Democratic Republic of the Congo', 'CD');
INSERT INTO public.countries (id, full_name, short_name) VALUES (40, 'Central African Republic', 'CF');
INSERT INTO public.countries (id, full_name, short_name) VALUES (41, 'Congo', 'CG');
INSERT INTO public.countries (id, full_name, short_name) VALUES (42, 'Switzerland', 'CH');
INSERT INTO public.countries (id, full_name, short_name) VALUES (43, 'Côte d''Ivoire', 'CI');
INSERT INTO public.countries (id, full_name, short_name) VALUES (44, 'Cook Islands', 'CK');
INSERT INTO public.countries (id, full_name, short_name) VALUES (45, 'Chile', 'CL');
INSERT INTO public.countries (id, full_name, short_name) VALUES (46, 'Cameroon', 'CM');
INSERT INTO public.countries (id, full_name, short_name) VALUES (47, 'China', 'CN');
INSERT INTO public.countries (id, full_name, short_name) VALUES (48, 'Colombia', 'CO');
INSERT INTO public.countries (id, full_name, short_name) VALUES (49, 'Costa Rica', 'CR');
INSERT INTO public.countries (id, full_name, short_name) VALUES (50, 'Cuba', 'CU');
INSERT INTO public.countries (id, full_name, short_name) VALUES (51, 'Cabo Verde', 'CV');
INSERT INTO public.countries (id, full_name, short_name) VALUES (52, 'Curaçao', 'CW');
INSERT INTO public.countries (id, full_name, short_name) VALUES (53, 'Christmas Island', 'CX');
INSERT INTO public.countries (id, full_name, short_name) VALUES (54, 'Cyprus', 'CY');
INSERT INTO public.countries (id, full_name, short_name) VALUES (55, 'Czechia', 'CZ');
INSERT INTO public.countries (id, full_name, short_name) VALUES (56, 'Germany', 'DE');
INSERT INTO public.countries (id, full_name, short_name) VALUES (57, 'Djibouti', 'DJ');
INSERT INTO public.countries (id, full_name, short_name) VALUES (58, 'Denmark', 'DK');
INSERT INTO public.countries (id, full_name, short_name) VALUES (59, 'Dominica', 'DM');
INSERT INTO public.countries (id, full_name, short_name) VALUES (60, 'Dominican Republic', 'DO');
INSERT INTO public.countries (id, full_name, short_name) VALUES (61, 'Algeria', 'DZ');
INSERT INTO public.countries (id, full_name, short_name) VALUES (62, 'Ecuador', 'EC');
INSERT INTO public.countries (id, full_name, short_name) VALUES (63, 'Estonia', 'EE');
INSERT INTO public.countries (id, full_name, short_name) VALUES (64, 'Egypt', 'EG');
INSERT INTO public.countries (id, full_name, short_name) VALUES (65, 'Western Sahara', 'EH');
INSERT INTO public.countries (id, full_name, short_name) VALUES (66, 'Eritrea', 'ER');
INSERT INTO public.countries (id, full_name, short_name) VALUES (67, 'Spain', 'ES');
INSERT INTO public.countries (id, full_name, short_name) VALUES (68, 'Ethiopia', 'ET');
INSERT INTO public.countries (id, full_name, short_name) VALUES (69, 'Finland', 'FI');
INSERT INTO public.countries (id, full_name, short_name) VALUES (70, 'Fiji', 'FJ');
INSERT INTO public.countries (id, full_name, short_name) VALUES (71, 'Falkland Islands (Malvinas)', 'FK');
INSERT INTO public.countries (id, full_name, short_name) VALUES (72, 'Micronesia (Federated States of)', 'FM');
INSERT INTO public.countries (id, full_name, short_name) VALUES (73, 'Faroe Islands', 'FO');
INSERT INTO public.countries (id, full_name, short_name) VALUES (74, 'France', 'FR');
INSERT INTO public.countries (id, full_name, short_name) VALUES (75, 'Gabon', 'GA');
INSERT INTO public.countries (id, full_name, short_name) VALUES (76, 'United Kingdom of Great Britain and Northern Ireland', 'GB');
INSERT INTO public.countries (id, full_name, short_name) VALUES (77, 'Grenada', 'GD');
INSERT INTO public.countries (id, full_name, short_name) VALUES (78, 'Georgia', 'GE');
INSERT INTO public.countries (id, full_name, short_name) VALUES (79, 'French Guiana', 'GF');
INSERT INTO public.countries (id, full_name, short_name) VALUES (80, 'Guernsey', 'GG');
INSERT INTO public.countries (id, full_name, short_name) VALUES (81, 'Ghana', 'GH');
INSERT INTO public.countries (id, full_name, short_name) VALUES (82, 'Gibraltar', 'GI');
INSERT INTO public.countries (id, full_name, short_name) VALUES (83, 'Greenland', 'GL');
INSERT INTO public.countries (id, full_name, short_name) VALUES (84, 'Gambia', 'GM');
INSERT INTO public.countries (id, full_name, short_name) VALUES (85, 'Guinea', 'GN');
INSERT INTO public.countries (id, full_name, short_name) VALUES (86, 'Guadeloupe', 'GP');
INSERT INTO public.countries (id, full_name, short_name) VALUES (87, 'Equatorial Guinea', 'GQ');
INSERT INTO public.countries (id, full_name, short_name) VALUES (88, 'Greece', 'GR');
INSERT INTO public.countries (id, full_name, short_name) VALUES (89, 'South Georgia and the South Sandwich Islands', 'GS');
INSERT INTO public.countries (id, full_name, short_name) VALUES (90, 'Guatemala', 'GT');
INSERT INTO public.countries (id, full_name, short_name) VALUES (91, 'Guam', 'GU');
INSERT INTO public.countries (id, full_name, short_name) VALUES (92, 'Guinea-Bissau', 'GW');
INSERT INTO public.countries (id, full_name, short_name) VALUES (93, 'Guyana', 'GY');
INSERT INTO public.countries (id, full_name, short_name) VALUES (94, 'Hong Kong', 'HK');
INSERT INTO public.countries (id, full_name, short_name) VALUES (95, 'Honduras', 'HN');
INSERT INTO public.countries (id, full_name, short_name) VALUES (96, 'Croatia', 'HR');
INSERT INTO public.countries (id, full_name, short_name) VALUES (97, 'Haiti', 'HT');
INSERT INTO public.countries (id, full_name, short_name) VALUES (98, 'Hungary', 'HU');
INSERT INTO public.countries (id, full_name, short_name) VALUES (99, 'Indonesia', 'ID');
INSERT INTO public.countries (id, full_name, short_name) VALUES (100, 'Ireland', 'IE');
INSERT INTO public.countries (id, full_name, short_name) VALUES (101, 'Israel', 'IL');
INSERT INTO public.countries (id, full_name, short_name) VALUES (102, 'Isle of Man', 'IM');
INSERT INTO public.countries (id, full_name, short_name) VALUES (103, 'India', 'IN');
INSERT INTO public.countries (id, full_name, short_name) VALUES (104, 'Iraq', 'IQ');
INSERT INTO public.countries (id, full_name, short_name) VALUES (105, 'Iran (Islamic Republic of)', 'IR');
INSERT INTO public.countries (id, full_name, short_name) VALUES (106, 'Iceland', 'IS');
INSERT INTO public.countries (id, full_name, short_name) VALUES (107, 'Italy', 'IT');
INSERT INTO public.countries (id, full_name, short_name) VALUES (108, 'Jersey', 'JE');
INSERT INTO public.countries (id, full_name, short_name) VALUES (109, 'Jamaica', 'JM');
INSERT INTO public.countries (id, full_name, short_name) VALUES (110, 'Jordan', 'JO');
INSERT INTO public.countries (id, full_name, short_name) VALUES (111, 'Japan', 'JP');
INSERT INTO public.countries (id, full_name, short_name) VALUES (112, 'Kenya', 'KE');
INSERT INTO public.countries (id, full_name, short_name) VALUES (113, 'Kyrgyzstan', 'KG');
INSERT INTO public.countries (id, full_name, short_name) VALUES (114, 'Cambodia', 'KH');
INSERT INTO public.countries (id, full_name, short_name) VALUES (115, 'Kiribati', 'KI');
INSERT INTO public.countries (id, full_name, short_name) VALUES (116, 'Comoros', 'KM');
INSERT INTO public.countries (id, full_name, short_name) VALUES (117, 'Saint Kitts and Nevis', 'KN');
INSERT INTO public.countries (id, full_name, short_name) VALUES (118, 'Korea (Democratic People''s Republic of)', 'KP');
INSERT INTO public.countries (id, full_name, short_name) VALUES (119, 'Republic of Korea', 'KR');
INSERT INTO public.countries (id, full_name, short_name) VALUES (120, 'Kuwait', 'KW');
INSERT INTO public.countries (id, full_name, short_name) VALUES (121, 'Cayman Islands', 'KY');
INSERT INTO public.countries (id, full_name, short_name) VALUES (122, 'Kazakhstan', 'KZ');
INSERT INTO public.countries (id, full_name, short_name) VALUES (123, 'Lao People''s Democratic Republic', 'LA');
INSERT INTO public.countries (id, full_name, short_name) VALUES (124, 'Lebanon', 'LB');
INSERT INTO public.countries (id, full_name, short_name) VALUES (125, 'Saint Lucia', 'LC');
INSERT INTO public.countries (id, full_name, short_name) VALUES (126, 'Liechtenstein', 'LI');
INSERT INTO public.countries (id, full_name, short_name) VALUES (127, 'Sri Lanka', 'LK');
INSERT INTO public.countries (id, full_name, short_name) VALUES (128, 'Liberia', 'LR');
INSERT INTO public.countries (id, full_name, short_name) VALUES (129, 'Lesotho', 'LS');
INSERT INTO public.countries (id, full_name, short_name) VALUES (130, 'Lithuania', 'LT');
INSERT INTO public.countries (id, full_name, short_name) VALUES (131, 'Luxembourg', 'LU');
INSERT INTO public.countries (id, full_name, short_name) VALUES (132, 'Latvia', 'LV');
INSERT INTO public.countries (id, full_name, short_name) VALUES (133, 'Libya', 'LY');
INSERT INTO public.countries (id, full_name, short_name) VALUES (134, 'Morocco', 'MA');
INSERT INTO public.countries (id, full_name, short_name) VALUES (135, 'Monaco', 'MC');
INSERT INTO public.countries (id, full_name, short_name) VALUES (136, 'Republic of Moldova', 'MD');
INSERT INTO public.countries (id, full_name, short_name) VALUES (137, 'Montenegro', 'ME');
INSERT INTO public.countries (id, full_name, short_name) VALUES (138, 'Saint Martin (French part)', 'MF');
INSERT INTO public.countries (id, full_name, short_name) VALUES (139, 'Madagascar', 'MG');
INSERT INTO public.countries (id, full_name, short_name) VALUES (140, 'Marshall Islands', 'MH');
INSERT INTO public.countries (id, full_name, short_name) VALUES (141, 'North Macedonia', 'MK');
INSERT INTO public.countries (id, full_name, short_name) VALUES (142, 'Mali', 'ML');
INSERT INTO public.countries (id, full_name, short_name) VALUES (143, 'Myanmar', 'MM');
INSERT INTO public.countries (id, full_name, short_name) VALUES (144, 'Mongolia', 'MN');
INSERT INTO public.countries (id, full_name, short_name) VALUES (145, 'Macao', 'MO');
INSERT INTO public.countries (id, full_name, short_name) VALUES (146, 'Northern Mariana Islands', 'MP');
INSERT INTO public.countries (id, full_name, short_name) VALUES (147, 'Martinique', 'MQ');
INSERT INTO public.countries (id, full_name, short_name) VALUES (148, 'Mauritania', 'MR');
INSERT INTO public.countries (id, full_name, short_name) VALUES (149, 'Montserrat', 'MS');
INSERT INTO public.countries (id, full_name, short_name) VALUES (150, 'Malta', 'MT');
INSERT INTO public.countries (id, full_name, short_name) VALUES (151, 'Mauritius', 'MU');
INSERT INTO public.countries (id, full_name, short_name) VALUES (152, 'Maldives', 'MV');
INSERT INTO public.countries (id, full_name, short_name) VALUES (153, 'Malawi', 'MW');
INSERT INTO public.countries (id, full_name, short_name) VALUES (154, 'Mexico', 'MX');
INSERT INTO public.countries (id, full_name, short_name) VALUES (155, 'Malaysia', 'MY');
INSERT INTO public.countries (id, full_name, short_name) VALUES (156, 'Mozambique', 'MZ');
INSERT INTO public.countries (id, full_name, short_name) VALUES (157, 'Namibia', 'NA');
INSERT INTO public.countries (id, full_name, short_name) VALUES (158, 'New Caledonia', 'NC');
INSERT INTO public.countries (id, full_name, short_name) VALUES (159, 'Niger', 'NE');
INSERT INTO public.countries (id, full_name, short_name) VALUES (160, 'Norfolk Island', 'NF');
INSERT INTO public.countries (id, full_name, short_name) VALUES (161, 'Nigeria', 'NG');
INSERT INTO public.countries (id, full_name, short_name) VALUES (162, 'Nicaragua', 'NI');
INSERT INTO public.countries (id, full_name, short_name) VALUES (163, 'Netherlands', 'NL');
INSERT INTO public.countries (id, full_name, short_name) VALUES (164, 'Norway', 'NO');
INSERT INTO public.countries (id, full_name, short_name) VALUES (165, 'Nepal', 'NP');
INSERT INTO public.countries (id, full_name, short_name) VALUES (166, 'Nauru', 'NR');
INSERT INTO public.countries (id, full_name, short_name) VALUES (167, 'Niue', 'NU');
INSERT INTO public.countries (id, full_name, short_name) VALUES (168, 'New Zealand', 'NZ');
INSERT INTO public.countries (id, full_name, short_name) VALUES (169, 'Oman', 'OM');
INSERT INTO public.countries (id, full_name, short_name) VALUES (170, 'Panama', 'PA');
INSERT INTO public.countries (id, full_name, short_name) VALUES (171, 'Peru', 'PE');
INSERT INTO public.countries (id, full_name, short_name) VALUES (172, 'French Polynesia', 'PF');
INSERT INTO public.countries (id, full_name, short_name) VALUES (173, 'Papua New Guinea', 'PG');
INSERT INTO public.countries (id, full_name, short_name) VALUES (174, 'Philippines', 'PH');
INSERT INTO public.countries (id, full_name, short_name) VALUES (175, 'Pakistan', 'PK');
INSERT INTO public.countries (id, full_name, short_name) VALUES (176, 'Poland', 'PL');
INSERT INTO public.countries (id, full_name, short_name) VALUES (177, 'Saint Pierre and Miquelon', 'PM');
INSERT INTO public.countries (id, full_name, short_name) VALUES (178, 'Pitcairn', 'PN');
INSERT INTO public.countries (id, full_name, short_name) VALUES (179, 'Puerto Rico', 'PR');
INSERT INTO public.countries (id, full_name, short_name) VALUES (180, 'Palestine', 'PS');
INSERT INTO public.countries (id, full_name, short_name) VALUES (181, 'Portugal', 'PT');
INSERT INTO public.countries (id, full_name, short_name) VALUES (182, 'Palau', 'PW');
INSERT INTO public.countries (id, full_name, short_name) VALUES (183, 'Paraguay', 'PY');
INSERT INTO public.countries (id, full_name, short_name) VALUES (184, 'Qatar', 'QA');
INSERT INTO public.countries (id, full_name, short_name) VALUES (185, 'Réunion', 'RE');
INSERT INTO public.countries (id, full_name, short_name) VALUES (186, 'Romania', 'RO');
INSERT INTO public.countries (id, full_name, short_name) VALUES (187, 'Serbia', 'RS');
INSERT INTO public.countries (id, full_name, short_name) VALUES (188, 'Russian Federation', 'RU');
INSERT INTO public.countries (id, full_name, short_name) VALUES (189, 'Rwanda', 'RW');
INSERT INTO public.countries (id, full_name, short_name) VALUES (190, 'Saudi Arabia', 'SA');
INSERT INTO public.countries (id, full_name, short_name) VALUES (191, 'Solomon Islands', 'SB');
INSERT INTO public.countries (id, full_name, short_name) VALUES (192, 'Seychelles', 'SC');
INSERT INTO public.countries (id, full_name, short_name) VALUES (193, 'Sudan', 'SD');
INSERT INTO public.countries (id, full_name, short_name) VALUES (194, 'Sweden', 'SE');
INSERT INTO public.countries (id, full_name, short_name) VALUES (195, 'Singapore', 'SG');
INSERT INTO public.countries (id, full_name, short_name) VALUES (196, 'Saint Helena, Ascension and Tristan da Cunha', 'SH');
INSERT INTO public.countries (id, full_name, short_name) VALUES (197, 'Slovenia', 'SI');
INSERT INTO public.countries (id, full_name, short_name) VALUES (198, 'Svalbard and Jan Mayen', 'SJ');
INSERT INTO public.countries (id, full_name, short_name) VALUES (199, 'Slovakia', 'SK');
INSERT INTO public.countries (id, full_name, short_name) VALUES (200, 'Sierra Leone', 'SL');
INSERT INTO public.countries (id, full_name, short_name) VALUES (201, 'San Marino', 'SM');
INSERT INTO public.countries (id, full_name, short_name) VALUES (202, 'Senegal', 'SN');
INSERT INTO public.countries (id, full_name, short_name) VALUES (203, 'Somalia', 'SO');
INSERT INTO public.countries (id, full_name, short_name) VALUES (204, 'Suriname', 'SR');
INSERT INTO public.countries (id, full_name, short_name) VALUES (205, 'South Sudan', 'SS');
INSERT INTO public.countries (id, full_name, short_name) VALUES (206, 'Sao Tome and Principe', 'ST');
INSERT INTO public.countries (id, full_name, short_name) VALUES (207, 'El Salvador', 'SV');
INSERT INTO public.countries (id, full_name, short_name) VALUES (208, 'Sint Maarten (Dutch part)', 'SX');
INSERT INTO public.countries (id, full_name, short_name) VALUES (209, 'Syrian Arab Republic', 'SY');
INSERT INTO public.countries (id, full_name, short_name) VALUES (210, 'Eswatini', 'SZ');
INSERT INTO public.countries (id, full_name, short_name) VALUES (211, 'Turks and Caicos Islands', 'TC');
INSERT INTO public.countries (id, full_name, short_name) VALUES (212, 'Chad', 'TD');
INSERT INTO public.countries (id, full_name, short_name) VALUES (213, 'French Southern Territories', 'TF');
INSERT INTO public.countries (id, full_name, short_name) VALUES (214, 'Togo', 'TG');
INSERT INTO public.countries (id, full_name, short_name) VALUES (215, 'Thailand', 'TH');
INSERT INTO public.countries (id, full_name, short_name) VALUES (216, 'Tajikistan', 'TJ');
INSERT INTO public.countries (id, full_name, short_name) VALUES (217, 'Tokelau', 'TK');
INSERT INTO public.countries (id, full_name, short_name) VALUES (218, 'Timor-Leste', 'TL');
INSERT INTO public.countries (id, full_name, short_name) VALUES (219, 'Turkmenistan', 'TM');
INSERT INTO public.countries (id, full_name, short_name) VALUES (220, 'Tunisia', 'TN');
INSERT INTO public.countries (id, full_name, short_name) VALUES (221, 'Tonga', 'TO');
INSERT INTO public.countries (id, full_name, short_name) VALUES (222, 'Turkey', 'TR');
INSERT INTO public.countries (id, full_name, short_name) VALUES (223, 'Trinidad and Tobago', 'TT');
INSERT INTO public.countries (id, full_name, short_name) VALUES (224, 'Tuvalu', 'TV');
INSERT INTO public.countries (id, full_name, short_name) VALUES (225, 'Taiwan', 'TW');
INSERT INTO public.countries (id, full_name, short_name) VALUES (226, 'Tanzania', 'TZ');
INSERT INTO public.countries (id, full_name, short_name) VALUES (227, 'Ukraine', 'UA');
INSERT INTO public.countries (id, full_name, short_name) VALUES (228, 'Uganda', 'UG');
INSERT INTO public.countries (id, full_name, short_name) VALUES (229, 'United States of America', 'US');
INSERT INTO public.countries (id, full_name, short_name) VALUES (230, 'Uruguay', 'UY');
INSERT INTO public.countries (id, full_name, short_name) VALUES (231, 'Uzbekistan', 'UZ');
INSERT INTO public.countries (id, full_name, short_name) VALUES (232, 'Holy See', 'VA');
INSERT INTO public.countries (id, full_name, short_name) VALUES (233, 'Saint Vincent and the Grenadines', 'VC');
INSERT INTO public.countries (id, full_name, short_name) VALUES (234, 'Venezuela (Bolivarian Republic of)', 'VE');
INSERT INTO public.countries (id, full_name, short_name) VALUES (235, 'Virgin Islands (British)', 'VG');
INSERT INTO public.countries (id, full_name, short_name) VALUES (236, 'Virgin Islands (U.S.)', 'VI');
INSERT INTO public.countries (id, full_name, short_name) VALUES (237, 'Viet Nam', 'VN');
INSERT INTO public.countries (id, full_name, short_name) VALUES (238, 'Vanuatu', 'VU');
INSERT INTO public.countries (id, full_name, short_name) VALUES (239, 'Wallis and Futuna', 'WF');
INSERT INTO public.countries (id, full_name, short_name) VALUES (240, 'Samoa', 'WS');
INSERT INTO public.countries (id, full_name, short_name) VALUES (241, 'Republic of Kosovo', 'XK');
INSERT INTO public.countries (id, full_name, short_name) VALUES (242, 'Yemen', 'YE');
INSERT INTO public.countries (id, full_name, short_name) VALUES (243, 'Mayotte', 'YT');
INSERT INTO public.countries (id, full_name, short_name) VALUES (244, 'South Africa', 'ZA');
INSERT INTO public.countries (id, full_name, short_name) VALUES (245, 'Zambia', 'ZM');
INSERT INTO public.countries (id, full_name, short_name) VALUES (246, 'Zimbabwe', 'ZW');
